name: Atualização Automática

on:
  push: # Quando algo for enviado manualmente
    branches:
      - master
  schedule: # Agendamento automático
    - cron: '*/5 * * * *' # Executa a cada 5 minutos

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar o repositório
      - name: Clonar o Repositório
        uses: actions/checkout@v3

      # 2. Configurar Git
      - name: Configurar Git
        run: |
          git config user.name "Kauê Enginer"
          git config user.email "elenacrae@gmail.com"

      # 3. Adicionar e Comitar Mudanças (se houver)
      - name: Adicionar e Comitar Mudanças (se houver)
        run: |
          git add .
          if git diff-index --quiet HEAD; then
            echo "Sem mudanças para comitar";
          else
            git commit -m "Atualização automática via GitHub Actions";
          fi

      # 4. Fazer Push
      - name: Fazer Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/SasoriAutoPecas/Tatical-board.git master
